name: Docker CI Pipeline

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build-and-test-image:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout the code
        uses: actions/checkout@v4

      - name: 2. Start services using Docker Compose
        run: docker compose up -d --build

      - name: 3. Check if the app is responding
        run: |
          sleep 10
          curl -f http://localhost:3000 || exit 1

      - name: 4. Clean up containers
        run: docker compose down